DG: false
FSGD: false
PCB: false
adv: 0.0
aiter: 10
arcface: false
batchsize: 1 # set batch size to 1 since we're processing a single image
circle: false
color_jitter: false
contrast: false
cosface: false
cosine: false
data_dir: ../Dataset
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids: '0'
ibn: false
ins_gamma: 32
instance: false
lifted: false
linear_num: 1024
lr: 0.05
name: swin
nclasses: 55
sphere: false
stride: 2
total_epoch: 300
train_all: true
triplet: false
use_NAS: false
use_convnext: false
use_dense: false
use_efficient: false
use_hr: false
use_swin: true
use_swinv2: false
warm_epoch: 0
weight_decay: 0.0005
